# Generated by Django 3.1.6 on 2021-09-09 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium_profile',
            name='created',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium_profile',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_player', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
                ('local_seats', models.IntegerField(blank=True, null=True)),
                ('vip_seats', models.IntegerField(blank=True, null=True)),
                ('platinum_seats', models.IntegerField(blank=True, null=True)),
                ('golden_seats', models.IntegerField(blank=True, null=True)),
                ('silver_seats', models.IntegerField(blank=True, null=True)),
                ('medium_seats', models.IntegerField(blank=True, null=True)),
                ('local_seats_price', models.IntegerField(blank=True, null=True)),
                ('vip_seats_price', models.IntegerField(blank=True, null=True)),
                ('silver_seats_price', models.IntegerField(blank=True, null=True)),
                ('golden_seats_price', models.IntegerField(blank=True, null=True)),
                ('platinum_seats_price', models.IntegerField(blank=True, null=True)),
                ('medium_seats_price', models.IntegerField(blank=True, null=True)),
                ('remaining_seats', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_created=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_for', models.DateField(blank=True, null=True)),
                ('total_seats', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
