# Generated by Django 3.2.6 on 2021-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0003_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stadium_profile',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
