# Generated by Django 3.2.6 on 2021-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0005_auto_20210909_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_choices',
            field=models.IntegerField(blank=True, choices=[(1, 'VIP'), (2, 'Local'), (3, 'Medium'), (4, 'Platinum'), (5, 'Silver'), (6, 'Golden')], null=True),
        ),
    ]
