# Generated by Django 3.1.6 on 2021-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0006_auto_20210911_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (1, 'Accepted'), (3, 'Canceled')], null=True),
        ),
    ]
