# Generated by Django 3.1.6 on 2021-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0007_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Canceled')], default=1, null=True),
        ),
    ]
