# Generated by Django 3.1.6 on 2021-09-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0008_auto_20210912_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stadium_profile',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
