# Generated by Django 3.1.6 on 2021-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0010_auto_20210914_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('contact_status', models.IntegerField(blank=True, choices=[(1, 'Read'), (2, 'UnRead')], default=2, null=True)),
            ],
        ),
    ]
