# Generated by Django 3.1.6 on 2021-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Read'), (2, 'UnRead')], default=2, null=True),
        ),
    ]
