# Generated by Django 3.1.6 on 2021-09-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0013_feedback_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
